import { Pokemon } from './pokemons';
  
export const POKEMONS: Pokemon[] = [
    {
        id: 1,
        name: "Bulbizarre",
        hp: 25,
        cp: 5,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/001.png",
        types: ["Plante", "Poison"],
        created: new Date(),
        rarity: 5,
        sound:"//www.pokepedia.fr/images/9/97/Cri_6_x_001.ogg",
    },
    {
        id: 2,
        name: "Salamèche",
        hp: 28,
        cp: 6,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/004.png",
        types: ["Feu"],
        created: new Date(),
        rarity: 5,
        sound:"//www.pokepedia.fr/images/c/cf/Cri_4_d_004.ogg",
    },
    {
        id: 3,
        name: "Carapuce",
        hp: 21,
        cp: 4,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/007.png",
        types: ["Eau"],
        created: new Date(),
        rarity: 4,
        sound:"//www.pokepedia.fr/images/f/f4/Cri_4_d_007.ogg",
    },
    {
        id: 4,
        name: "Aspicot",
        hp: 16,
        cp: 2,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/013.png",
        types: ["Insecte", "Poison"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/a/a6/Cri_4_d_013.ogg",
    },
    {
        id: 5,
        name: "Roucool",
        hp: 30,
        cp: 7,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/016.png",
        types: ["Normal", "Vol"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/b/b0/Cri_4_d_016_2.ogg",
    },
    {
        id: 6,
        name: "Rattata",
        hp: 18,
        cp: 6,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/019.png",
        types: ["Normal"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/e/e5/Cri_4_d_019_2.ogg",
    },
    {
        id: 7,
        name: "Piafabec",
        hp: 14,
        cp: 5,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/021.png",
        types: ["Normal", "Vol"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/3/36/Cri_4_d_021.ogg",
    },
    {
        id: 8,
        name: "Abo",
        hp: 16,
        cp: 4,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/023.png",
        types: ["Poison"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/e/e7/Cri_4_d_023.ogg",
    },
    {
        id: 9,
        name: "Pikachu",
        hp: 21,
        cp: 7,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/025.png",
        types: ["Electrik"],
        created: new Date(),
        rarity: 5,
        sound:"//www.pokepedia.fr/images/e/ec/Cri_4_d_025.ogg",
    },
    {
        id: 10,
        name: "Sabelette",
        hp: 19,
        cp: 3,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/027.png",
        types: ["Normal"],
        created: new Date(),
        rarity: 1,
        sound:"//www.pokepedia.fr/images/1/14/Cri_4_d_027.ogg",
    },
    {
        id: 11,
        name: "Mélofée",
        hp: 25,
        cp: 5,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/035.png",
        types: ["Fée"],
        created: new Date(),
        rarity: 3,
        sound:"//www.pokepedia.fr/images/d/dc/Cri_035_EB.ogg",
    },
    {
        id: 12,
        name: "Goupix",
        hp: 17,
        cp: 8,
        picture: "https://assets.pokemon.com/assets/cms2/img/pokedex/detail/037.png",
        types: ["Feu"],
        created: new Date(),
        rarity: 2,
        sound:"//www.pokepedia.fr/images/f/fe/Cri_4_d_037.ogg",
    }
];